### ISSUE TITLE
Fatal error: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by gabrielmaldi** [gruntjs/grunt-contrib-imagemin#320] opened 2015-09-17 15:32 UTC
I'm getting `Fatal error: Cannot read property 'length' of null` on images that I've optimized with [TinyPNG](https://tinypng.com/) (but aren't corrupt). Here's an example image:

![myimage](https://cloud.githubusercontent.com/assets/3728897/9937506/70a11058-5d37-11e5-85c3-e7424980db62.png)

`ImageMagick's` `identify` outputs `myImage.png PNG 29x29 29x29+0+0 8-bit sRGB 28c 409B 0.000u 0:00.000` so the image appears to be valid, but `imagemin` has trouble with it.

I'm using `grunt-contrib-imagemin v0.9.4`.

Thanks!

**Comment by sindresorhus** [comment] 2015-12-23 02:34
Does this still happen with 1.0.0?

**Comment by nleclerc** [comment] 2016-01-27 17:59
I get the same error on 1.0.0.

**Comment by nleclerc** [comment] 2016-01-27 18:00
Ah no, not same, it's `property 'contents' of undefined`.
Caused by a png file also.

**Comment by acasademont** [comment] 2016-03-02 12:42
same here :(

**Comment by acasademont** [comment] 2016-03-02 12:49
btw, it seems to be working on my Debian 7 environment,  but 8 fails, weird, any hints?

**Comment by davidmaxwaterman** [comment] 2016-04-06 07:34
It's probably a different situation, but I figured I'd add this here in case anyone else comes across it.

I had this error and through adding console.log()s to print the filename in the imagemin task (node_modules/grunt-contrib-imagemin/tasks/imagemin.js), I found that the error was produced when the task was given a directory rather than a file (ie app/images). This was due to lines in my Gruntfile :

```
        files: [
          { expand: true, cwd: '.', src: ['app/images/**'], dest: 'build/' },
          { expand: true, cwd: '.', src: ['app/css/images/**'], dest: 'build/' }
        ]
```

When I changes them to (note the extra `/*` on the `src`):

```
        files: [
          { expand: true, cwd: '.', src: ['app/images/**/*'], dest: 'build/' },
          { expand: true, cwd: '.', src: ['app/css/images/**/*'], dest: 'build/' }
        ]
```

all worked as before.

**Comment by vivekkodira1** [comment] 2016-05-12 06:46
I was still encountering this error despite changing the path as above. Changed the following line to get past it. 

Before
`var diffSize = origSize - data[0].contents.length;`

After
`var diffSize = origSize - ( ( data[0].contents && data[0].contents.length) || origSize );`

**Comment by kevva** [comment] 2016-05-23 15:20
Fixed in https://github.com/gruntjs/grunt-contrib-imagemin/commit/92963f19069bff79b9d1d3f32ff282745ace538c.

**Closed by kevva** 2016-05-23 15:20 UTC
