### ISSUE TITLE
Fatal error: Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by douglasdeodato** [gruntjs/grunt-contrib-imagemin#330] opened 2015-11-09 11:19 UTC
i am getting that error after run: grunt imagemin

Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined

the funnest part is: i am using the same code and images from other project for test and in that projects everything works perfect. \o/ 
i tried use --force but keeps the same error, the task minimize one image but not all.

my gruntfile.js
//Image min ===============================

				var imagemin;
				config.imagemin = imagemin = {};

					imagemin.dist = {
								  options: {
						          optimizationLevel: 5,
						          progressive: true,
						      },
						
					        files: [{
					            expand: true,
					            cwd: 'public/images/',
					            src: ['**/*.{png,jpg,gif}'],
					            dest: 'public/images/min'
					        }]
					 };

**Comment by tobigit** [comment] 2015-11-09 12:02
+1

**Comment by sergioadorna** [comment] 2015-11-09 12:09
Same for me, everything works in an outdated version, but if I run npm install and use new updates will get this error...

I think is something related to the function used to calculate size differences between source and output files.

if I check for undefined data[0] in this anonymous function: node_modules/grunt-contrib-imagemin/tasks/imagemin.js:48

the "fix" since the image size difference still won't be calculated:
```
if (data[0] === undefined) {
    grunt.warn('could not calculate size difference' + ' in file ' + file.src[0]);
    return next();
}
```

the anonymous callback function to put the fix:
```
fs.stat(file.src[0], function (err, stats) {
                if (err) {
                    grunt.warn(err + ' in file ' + file.src[0]);
                    return next();
                }

                imagemin.run(function (err, data) {
                    console.log(arguments);
                    if (err) {
                        grunt.warn(err + ' in file ' + file.src[0]);
                        return next();
                    }

                    var origSize = stats.size;
                    var diffSize = origSize - data[0].contents.length;

                    totalSaved += diffSize;

                    if (diffSize < 10) {
                        msg = 'already optimized';
                    } else {
                        msg = [
                            'saved ' + prettyBytes(diffSize) + ' -',
                            (diffSize / origSize * 100).toFixed() + '%'
                        ].join(' ');
                    }

                    grunt.verbose.writeln(chalk.green('✔ ') + file.src[0] + chalk.gray(' (' + msg + ')'));
                    process.nextTick(next);
                });
            });
```

Guess why ```data``` argument is undefined when ```err``` is null I think is the key to really fix this...

**Comment by steveu** [comment] 2015-11-09 12:29
+1
Same error here (was working on Friday with fresh npm install).

**Comment by sergioadorna** [comment] 2015-11-09 12:41
I have dig enough to know that the error is not in grunt-contrib-imagemin or imagemin libraries, as it seems to be an error in concat-stream or one of its dependencies... I will keep digging, any help would be appreciated... :smile:

**Comment by scottmerker** [comment] 2015-11-09 13:26
Same error here.  Latest is broken.

**Comment by douglasdeodato** [comment] 2015-11-09 14:07
hey guys, that error happen at version:  "name": "imagemin",
  "version": "3.2.2",

if you use  "name": "imagemin",
  "version": "3.2.0",  will works fine.

some stuff i notice too:

dependencies
 "through2": "^0.6.1", was removed  from the old version and replaced for:  "readable-stream": "^2.0.0",

as well: "meow": "^3.3.0" was updated on that version, anyway maybe can be that depedencies?

**Comment by jorrit** [comment] 2015-11-09 14:16
It could also be a minor dependency update in one of the dependencies that will be pulled in when you reinstall your node_modules folder.

**Comment by kupiodigital** [comment] 2015-11-09 14:47
Same for me. My build works locally, but when deploying via codeship (Which does a fresh npm install each time) it fails.

Feels like a minor dependency somewhere in the tree which has been changed.

**Comment by jorrit** [comment] 2015-11-09 14:57
@kupiodigital what is your output of `npm  list` locally?

**Comment by mlegenhausen** [comment] 2015-11-09 15:05
+1

**Comment by jorrit** [comment] 2015-11-09 15:05
Isn't this the same as #325, by the way?

**Comment by kupiodigital** [comment] 2015-11-09 15:08
Bearing in mind that it's probably been quite some time since I actually updated anything locally, (So there may be a large number of old version numbers) I've uploaded the relevant portion here: http://www.kupio.com/dump/imagemin-npm-ls.zip

(Don't have permission to attach files to comments here)

**Comment by douglasdeodato** [comment] 2015-11-09 15:08
@jorrit  is not: the output error is: Running "imagemin:dist" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined

**Comment by kupiodigital** [comment] 2015-11-09 16:05
If it helps, this worked for me on 6 November, so whatever package was updated, it would have been updated on or after that date.

**Comment by sergioadorna** [comment] 2015-11-09 16:20
this fixes this issue...
https://github.com/gruntjs/grunt-contrib-imagemin/pull/329
let's see how long until it gets merged

**Comment by JoeWheats** [comment] 2015-11-09 16:39
Reverting to version 0.8.0 worked for me. Not a fix just a workaround!

**Comment by ernestorocha** [comment] 2015-11-09 18:41
0.9.2 it's not working but 0.9.1 is. How is this possible ? Everything has the version locked and wasn't not updated for months on my project!

**Comment by philwolstenholme** [comment] 2015-11-09 20:31
Fixed in #329 / 212ec999c69d62e229c83f115d3b2026ffd3f122

**Comment by Chexpir** [comment] 2015-11-10 09:36
I agree it is fixed. I'd close this ticket.

**Closed** 2015-11-10 21:18 UTC

**Comment by nesiri** [comment] 2016-01-12 04:14
This issue is reoccurring with grunt-contrib-imagemin version 1.0.0.

**Comment by kzko** [comment] 2016-01-12 06:04
same here ... error ocurring on grunt-contrib-imagemin V1.0.0 and imagemin V3.2.2 pair

**Comment by vampolo** [comment] 2016-01-12 08:23
I can confirm it is happening again, relevant deps

```
─┬ grunt-contrib-imagemin@1.0.0
│ ├─┬ chalk@1.1.1 
│ │ ├── ansi-styles@2.1.0 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.0.0 
│ │ ├── strip-ansi@3.0.0 
│ │ └── supports-color@2.0.0 
│ └─┬ imagemin@4.0.0
```

**Comment by arenoux** [comment] 2016-01-12 09:43
Same for us :
```
grunt-contrib-imagemin@1.0.0 node_modules/grunt-contrib-imagemin
├── gulp-rename@1.2.2
├── async@0.9.2
├── chalk@1.1.1 (escape-string-regexp@1.0.4, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.7.0)
└── imagemin@4.0.0 (optional@0.1.3, stream-combiner2@1.1.1, concat-stream@1.5.1, buffer-to-vinyl@1.1.0, readable-stream@2.0.5, vinyl-fs@2.3.0, imagemin-gifsicle@4.2.0, imagemin-optipng@4.3.0, imagemin-jpegtran@4.3.2, imagemin-svgo@4.2.0)
```

**Comment by matteofuzz** [comment] 2016-01-12 09:57
Same here:
```
├─┬ grunt-contrib-imagemin@1.0.0
│ ├── async@0.9.2 
│ ├─┬ imagemin@4.0.0
```

**Comment by giamma13** [comment] 2016-01-12 10:01
Same issue here as well
I used a workaround on a forked repo
* https://github.com/giamma13/grunt-contrib-imagemin/commit/29cc26ef35c528bc578132bc5c2857f7308aeebb

**Comment by jorrit** [comment] 2016-01-12 10:12
Thanks to this issue I was able to save the list of working modules before reinstalling everything. The only dependency that got changed was `vinyl-fs`. I got grunt imagemin working by downgrading vinyl-fs to 2.2.1 instead of 2.3.0.

**Comment by jorrit** [comment] 2016-01-12 10:31
@sindresorhus @vladikoff can you reopen this issue?

**Comment by 3urdoch** [comment] 2016-01-12 10:35
Just started getting this issue this morning with no changes in my project config. So a dependency update seems a likely cause.

**Comment by MonsJovis** [comment] 2016-01-12 10:50
Same issue since this morning:
```
grunt-contrib-imagemin@1.0.0 node_modules/grunt-contrib-imagemin
├── gulp-rename@1.2.2
├── async@0.9.2
├── chalk@1.1.1 (supports-color@2.0.0, ansi-styles@2.1.0, escape-string-regexp@1.0.4, strip-ansi@3.0.0, has-ansi@2.0.0)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.7.0)
└── imagemin@4.0.0 (optional@0.1.3, stream-combiner2@1.1.1, concat-stream@1.5.1, buffer-to-vinyl@1.1.0, readable-stream@2.0.5, vinyl-fs@2.3.0, imagemin-optipng@4.3.0, imagemin-svgo@4.2.0, imagemin-jpegtran@4.3.2, imagemin-gifsicle@4.2.0)
```
```
Running "imagemin:themes" (imagemin) task
Verifying property imagemin.themes exists in config...OK
Files: ./wp-content/themes/mytheme/screenshot.png -> wp-content/themes/mytheme/screenshot.png
Options: interlaced, optimizationLevel=3, progressive, svgoPlugins=[{"removeViewBox":false,"removeUselessStrokeAndFill":true,"removeEmptyAttrs":true}]
Fatal error: Cannot read property 'contents' of undefined
```

**Comment by pm-pramod-baddurkar** [comment] 2016-01-12 10:57
Same issue occurred again since morning. vinyl-fs dependency got updated from 2.2.1 to 2.3.0 . So for now ,got it fixed by adding "vinyl-fs": "2.2.1" in dependencies .

**Comment by juliusosokinas** [comment] 2016-01-12 11:37
:+1:

**Comment by icchio** [comment] 2016-01-12 12:42
"...adding "vinyl-fs": "2.2.1" in dependencies...." solve also for me!!

**Comment by antweiss** [comment] 2016-01-12 12:48
confirmed - locking vinyl-fs to 2.2.1 solves this

**Comment by amaurybrisou** [comment] 2016-01-12 12:55
:+1:

**Comment by vampolo** [comment] 2016-01-12 13:10
@pm-pramod-baddurkar out of curiosity. how did you spot that was exactly that dep to got an update ?

Anyway locking vinyl-fs to 2.2.1 works for me too

**Comment by pm-pramod-baddurkar** [comment] 2016-01-12 13:16
@vampolo i got this error while deploying on staging server and fortunately i had node_module for my project locally on which through which i was able to complete the build. So compared the npm list of two , i got to know about this change as a immediate dependency of imagemin.

**Comment by warpdesign** [comment] 2016-01-12 13:42
Adding "`vinyl-fs": "2.2.1"`as devDepenency fixed the problem for me.

**Comment by HenrikFricke** [comment] 2016-01-12 14:41
i had the same problem since version 1.0.0

**Comment by eloirobe** [comment] 2016-01-12 15:33
I have the same problem:

├┬ grunt-contrib-imagemin@1.0.0
├┬ imagemin@4.0.0
│ ├┬ imagemin-gifsicle@4.2.0
│ ├┬ imagemin-jpegtran@4.3.2
│ ├┬ imagemin-optipng@4.3.0
│ ├┬ imagemin-svgo@4.2.0


<img width="488" alt="fasdfa" src="https://cloud.githubusercontent.com/assets/11217675/12267643/6f2cb0f6-b949-11e5-8229-1257dae3ff89.png">

**Comment by cjennison** [comment] 2016-01-12 15:39
Putting "vinyl-fs": "2.2.1" into package.json as a dependency did it for me just as @antweiss mentioned.

**Comment by tfvictorino** [comment] 2016-01-12 17:01
Adding "vinyl-fs": "2.2.1" to the dependency list worked here too.

**Comment by kzko** [comment] 2016-01-12 17:16
Thanks, adding "vinyl-fs": "2.2.1" to dependency resolved the issue 

to verified that you've downgraded correctly
npm list vinyl-fs
npm view vinyl-fs version

**Comment by tanzaho** [comment] 2016-01-12 18:00
Thanks for the verification tip @kzko. 
I added "vinyl-fs": "2.2.1" into package.json , however, I'm getting the following : 
npm list vinyl-fs
└── vinyl-fs@2.2.1
npm view vinyl-fs version
2.3.0

I'm still getting the error message.
I'm not sure what to do to get the correct version locally (I tried to erase node_modules and then npm install everything).

**Comment by jimmydave03** [comment] 2016-01-12 19:08
Thanks guys, Adding "vinyl-fs": "2.2.1"as devDepenency fixed the problem for me also.

**Comment by rywalsh** [comment] 2016-01-12 21:27
Adding "vinyl-fs": "2.2.1"as dependency was the answer for me too. cheers!

**Comment by vivekpathak** [comment] 2016-01-12 21:31
yes works with explicit dependency added.  any way i can add this issue as a unit test case for this package? seems that it was broken, fixed, and now broken again.   any suggestions on how to go about this would be great.

**Comment by baikon** [comment] 2016-01-12 21:33
adding vinyl-fs as a dependency does not work

**Comment by RadoRado** [comment] 2016-01-12 21:46
`"vinyl-fs": "2.2.1"` works (for now) :panda_face:

**Comment by Angularism** [comment] 2016-01-12 23:05
First I removed all by 
npm uninstall vinyl-fs
npm uninstall imagemin

I edited my package.json as suggested and added "vinyl-fs": "2.2.1" under devDepenency

npm install
grunt build  (and all working!)

I suggest this project use fix version for dependency to avoid this in future.

**Comment by schmod** [comment] 2016-01-13 00:50
> I suggest this project use fix version for dependency to avoid this in future.

I got shot down when I suggested that in #331.

Strictly speaking, the reasons for the rejection were correct, but it has basically made it impossible for us to use this library (and many others) in production.  One of the many ways that the NPM ecosystem seems to actively discourage stability....

**Comment by boxhead201** [comment] 2016-01-13 03:28
I am now hit with this issue

├─┬ grunt-contrib-imagemin@1.0.0
│ ├── gulp-rename@1.2.2
│ ├─┬ imagemin@4.0.0
│ │ ├─┬ buffer-to-vinyl@1.1.0

**Comment by anbestephen** [comment] 2016-01-13 03:33
I have similar configuration. It is working in my local computer , but having issue runinng in travic-ci environment

**Comment by eloirobe** [comment] 2016-01-13 07:59
yes works using  "vinyl-fs": "2.2.1" as dependency

**Comment by stephanfriedrich** [comment] 2016-01-13 11:22
+1, get the same error.
with different node versions (0.12, 4.x, 5x).

grunt-contrib-imagemin@1.0.0
  └─┬ imagemin@4.0.0
    └── vinyl-fs@2.3.0

*it seem's imagemin have a broken dependencie to vinyl-fs version 2.3.0 *
https://github.com/imagemin/imagemin/issues/147

**Comment by konstantin24121** [comment] 2016-01-13 13:30
Have same problem. Using "vinyl-fs" not working for me. (node 0.12, win10)

**Comment by juliusosokinas** [comment] 2016-01-13 13:59
@konstantin24121, make sure to add 2.2.1 version of vinyl-fs to your local devDependencies.

**Comment by anbestephen** [comment] 2016-01-13 14:39
@juliusosokinas i added vinyl-fs@2.2.1 to my devDependencies but still i am failing to pass travis-ci build. Could you  post a working code snippet please?

**Comment by ernestorocha** [comment] 2016-01-13 14:44
@anbestephen be sure to have a line exactly like this `"vinyl-fs": "2.2.1"` and probably you'll have to delete your `node_modules` to clear previous installations.

**Comment by giamma13** [comment] 2016-01-13 14:46
But can we expect a proper fix from this package owner ?
without everybody having to add extra dependencies

**Comment by juliusosokinas** [comment] 2016-01-13 14:51
@anbestephen, to be honest, I just did that... I'm not using vinyl-fs for anything, but adding "vinyl-fs": "2.2.1" at the end of a list of devDependencies helped. Also, on Travis CI script after "npm install" I do "npm cache clean", only then "grunt". Try that! And if this does not work, try posting a link to your Travis CI task and to the repository itself, maybe someone here will help you.

**Comment by jorrit** [comment] 2016-01-13 14:53
The fix should be made in imagemin and/or vinyl-fs. This grunt plugin does not cause the problem, it is the victim of the bug created in vinyl-fs. See imagemin/imagemin#147.

**Comment by sisu4u** [comment] 2016-01-13 15:11
+1
Thanks for the workaround. Hopefully they'll fix imagemin soon.

**Comment by anbestephen** [comment] 2016-01-13 15:30
@juliusosokinas  here is [travis-ci build](https://travis-ci.org/raeprojects/www-raeprojects-org/builds/102118900) and [my repository](https://github.com/raeprojects/www-raeprojects-org). I am able to build locally , but i can't success travis-ci build. Can any one look at this and help?

**Comment by juliusosokinas** [comment] 2016-01-13 15:38
@anbestephen, I would try removing "npm install --save imagemin@3.2.2" from Travis CI, also in my case I added vinyl-fs straight to package.json, I haven't tried to manually install it with a command line (even though it should not matter, but...) :)

**Comment by anbestephen** [comment] 2016-01-13 15:45
@juliusosokinas thanks for your help, but still [travis-ci](https://travis-ci.org/raeprojects/www-raeprojects-org/builds/102129061) is failing

**Comment by juliusosokinas** [comment] 2016-01-13 15:48
@anbestephen I can confirm that vinyl-fs must be added to package.json, otherwise it fails for me too (with npm install vinyl-fs@2.2.1).

**Comment by anbestephen** [comment] 2016-01-13 16:10
@juliusosokinas i have made the changes what you suggested but still failling with this [build log](https://travis-ci.org/raeprojects/www-raeprojects-org/builds/102134336) , anyway thanks for your time

**Comment by lorijoan** [comment] 2016-01-13 16:17
@anbestephen - did you definitely your node_modules?

The grunt-contrib-imagemin has its own node_modules folder that will store the bad vinyl-fs.

**Comment by anbestephen** [comment] 2016-01-13 16:22
@lorijoan it is working in my local build, but it is failing in [travis-ci](https://travis-ci.org/raeprojects/www-raeprojects-org/builds/102134336), i have also running 'npm cache clean' after 'npm install', i didn't get ' did you definitely your node_modules???. Is there any thing i can to do that helps?

**Comment by lorijoan** [comment] 2016-01-13 16:26
Sorry - that should've said delete in the front.  Eg - delete the node_modules folder on the travis-ci agent.

That's what I had to do on my CI to get it working properly, although I didn't try npm cache clean to be fair.

**Comment by anbestephen** [comment] 2016-01-13 16:41
@lorijoan I added 'rm -R node_modules/vinyl-fs/node_modules/' to remove node_modules to .travis.yml file, but still travis-ci is failing with different [error log](https://travis-ci.org/raeprojects/www-raeprojects-org/builds/102142631) , could you please look at this log. Here is the [repository](https://github.com/raeprojects/www-raeprojects-org)

**Comment by lorijoan** [comment] 2016-01-13 16:49
@anbestephen - it seems like your build (in that log and even in the previous one) is still getting 2.3.0 of vinyl-fs.  I'd suspect the fact you remove the node_modules much later after where the npm installs look like they're happening probably is causing the newest build failure.

I'm not sure how travis-ci works - are you not able to just log onto the running agent and delete that way rather than trying to run it within a build like this?

**Comment by anbestephen** [comment] 2016-01-13 16:54
@lorijoan if you can ,  could you please post a snippet that you think it works. thanks

**Comment by juliusosokinas** [comment] 2016-01-13 17:10
Try to remove "^" when specifying a version of vinyl-fs, you need version 2.2.1 but not higher.

I didn't need to remove node_modules.

**Comment by blunatic** [comment] 2016-01-13 17:47
I mistakenly was changing the root level package.json to have "vinyl-fs": "2.2.1" as dependency...I had to specifically fix it at grunt-contrib-imagemin/node_modules/imagemin/package.json in order for it to begin working correctly.

**Comment by anbestephen** [comment] 2016-01-13 17:57
it works :+1:  !!!! after removing "^" when specifying a version of vinyl-fs in package.json file , it builds successfully with this [build-log](https://travis-ci.org/raeprojects/www-raeprojects-org/builds/102158965). Thanks @juliusosokinas , @lorijoan , @ernestorocha and everybody else.

**Comment by GitScrum** [comment] 2016-01-13 18:00
npm i -D imagemin vinyl-fs@2.2.1  works for me.

**Comment by konstantin24121** [comment] 2016-01-13 18:10
@juliusosokinas local in my package.json or in pacege.json into grunt-conrib-imagemin?

**Comment by vpravo** [comment] 2016-01-13 18:21
+1: npm i -D imagemin vinyl-fs@2.2.1 works for me too.

**Comment by juliusosokinas** [comment] 2016-01-13 20:12
@konstantin24121, your root (created by you) package.json file. But also try @GitScrum's solution.

**Comment by tony0918** [comment] 2016-01-14 03:48
confirmed - locking vinyl-fs to 2.2.1 solves this

**Comment by konstantin24121** [comment] 2016-01-15 06:57
@juliusosokinas @GitScrum thank's! @GitScrum solution work for me

**Comment by hypery2k** [comment] 2016-01-15 08:19
the problem exits with NPM 2.x

**Comment by jorrit** [comment] 2016-01-15 09:15
Locking to vinyl-fs 2.2.1 should no longer be necessary, vinyl-fs 2.3.1 fixes this.

**Comment by juliusosokinas** [comment] 2016-01-15 09:57
Can confirm that it has been fixed.

**Comment by tfvictorino** [comment] 2016-01-15 11:52
Can confirm that removing vinyl 2.2.1 worked here as well.

**Comment by lashan** [comment] 2016-01-15 16:42
1. Delete `node_modules`
2. Change `package.json` to use `"grunt-contrib-imagemin": "1.0.0"` and `"vinyl-fs": "2.3.1"`
3. Do `npm install`

That's what did it for me.

**Comment by jorrit** [comment] 2016-01-15 21:16
You can leave out `vinyl-fs` from package.json, unless you never want to upgrade beyond 2.3.1. npm will automatically download 2.31.

**Comment by mikeyfreake** [comment] 2016-02-22 00:42
Running `npm cache clean && npm install grunt-contrib-imagemin` worked for me. Thx

**Comment by musophob** [comment] 2016-03-15 11:59
I resolved this by bumping `grunt-contrib-imagemin` in `package.json` to `^1.0.0`, then givin' it the ol' `npm cache clean && npm install grunt-contrib-imagemin`.

**Comment by son1112** [comment] 2016-04-04 15:06
@lashan These steps worked for me.

**Comment by hliberato** [comment] 2016-04-25 19:44
Worket with @musophob tip.

**Comment by crmpicco** [comment] 2016-05-06 01:55
@lashan 's suggestion worked for me too.

```
Running "less:all" (less) task
>> 1 stylesheet created.

Running "copy:fonts" (copy) task
Copied 12 files

Running "imagemin:images" (imagemin) task
Minified 6 images (saved 12.67 kB)

Running "copy:bootstrapfonts" (copy) task
Copied 5 files

Running "jshint:all" (jshint) task
>> 7 files lint free.

Running "uglify:build" (uglify) task
>> 1 file created.

Running "bump" task
>> Updated asset version file to 1462499650

Done, without errors.
```

**Comment by ismusidhu** [comment] 2016-06-18 17:21
Taking clue from[ @mikeyfreake 's](#issuecomment-186953396) reply, I deleted %AppData%\Roaming\npm-cache\grunt-contrib_imagemin and then `npm install grunt-contrib-imagemin`. That worked for me on windows 10.

**Comment by AlexHenkel** [comment] 2016-08-08 19:03
@lashan Awesome, it worked with your tips
