### ISSUE TITLE
grunt-contrib-imagemin failed with  "gifsicle@0.1.7" 

### ISSUE THREAD

**Issue by XinliGuan** [gruntjs/grunt-contrib-imagemin#314] opened 2015-07-27 16:01 UTC
My name is Charley and working in IBM, I work with my partner to build a clamari GUI client file with the instruction in https://github.com/ceph/romana

My build environment is: 
[root@acme64 ~]# node --version
v0.12.7
[root@acme64 ~]# npm --version
2.13.2
[root@acme64 ~]# grunt --version
grunt-cli v0.1.13
[root@acme64 ~]# gem --version
1.8.24
[root@acme64 ~]# bower --version
1.4.1
[root@acme64 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.6 (Santiago)
[root@acme64 ~]#

In the last step it failed in make build-real with the error message:

> gifsicle@0.1.7 postinstall /temp/calamari-repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/node_modules/gifsicle
> node index.js

â  pre-build test failed, compiling from source...
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ˆ
Error: invalid tar file
    at Extract.Parse._startEntry (/temp/calamari-repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:145:13)
    at Extract.Parse._process (/temp/calamari-repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:127:12)
    at BlockStream.<anonymous> (/temp/calamari-repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/parse.js:47:8)
    at BlockStream.emit (events.js:107:17)
    at BlockStream._emitChunk (/temp/calamari-repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.resume (/temp/calamari-repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/block-stream/block-stream.js:58:15)
    at Extract.Reader.resume (/temp/calamari-repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream/lib/reader.js:255:34)
    at DirWriter.<anonymous> (/temp/calamari-repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/lib/extract.js:57:8)
    at DirWriter.emit (events.js:104:17)
    at /temp/calamari-repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream/lib/dir-writer.js:39:8

> pngquant-bin@0.1.7 postinstall /temp/calamari-repo/calamari-clients/manage/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin
> node index.js

â pre-build test passed successfully
npm ERR! Linux 2.6.32-504.30.3.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--loglevel" "warn"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@0.1.7 postinstall script 'node index.js'.
npm ERR! This is most likely a problem with the gifsicle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gifsicle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /temp/calamari-repo/calamari-clients/manage/npm-debug.log
make[1]: **\* [build-stamp] Error 1

Could you please help me to find the root cause of this issue and provide the resolution?

Thanks a lot;

Charley

**Comment by XinliGuan** [comment] 2015-07-27 16:22
This is my grant and grunt-cli configuration, n the wen it says that the grunt release should be >= 0.4.0
[root@acme64 node_modules]# grunt imagemin --version
grunt-cli v0.1.13
grunt v0.4.5
[root@acme64 node_modules]# grunt compass --version
grunt-cli v0.1.13
grunt v0.4.5
[root@acme64 node_modules]#

**Comment by AlphaHasi** [comment] 2015-08-10 14:00
Same problem here, grunt-contrib-imagemin version 0.9.4 works for png/jpg/svg but stops with "Fatal error: write EPIPE" when using it for gif.

grunt-cli v0.1.13
grunt v0.4.5
npm v2.13.3
node v0.10.33
Mac OS X Yosemite, v 10.10.4

My tasks are defined with ther help of jit-grunt ("^0.9.1")  and load-grunt-config ("^0.17.2").

(I also can't get the full output (where it lists the file names etc.) it only says "Minified X images (saved X kB)", but this might be some missing option I can't find.)

**Comment by AlphaHasi** [comment] 2015-10-22 12:17
I got a solution that works for me:

imagemin includes gifsicle, that causes this issue. I deinstalled imagemin (may not be necessary), installed gifsicle, installed imagemin again. Now it is not using the included gifsicle package but the seperatly installed one. The error is gone. (But I assume that the issue in general is still there.)

I know that I don't pay for a service, but still it is a bit strange that there is no reaction at all from the contributers. At least the issue could be closed, or commented as not reproducable or not important. So it looks that nobody cares for issues and the project is dead.

**Comment by praveenraj1987** [comment] 2016-11-25 11:36
Still this issue is open. Same problem here.
grunt --version
grunt-cli v1.2.0
grunt v0.4.5

**Comment by Protosac** [comment] 2016-11-30 23:29
Check your node versions. It appears this package isn't supported by the latest LTS, but thats the only one I checked. Package works fine with Node 4. It'd be a good idea to recheck the node dependencies for this package. Especially since this error hasn't gone away.

**Comment by cse-tushar** [comment] 2017-03-02 07:06
I had the issue on Ubuntu 16.04, fixed after installing gifsicle using command`sudo apt-get install gifsicle`.

after that grunt-contrib-imagemin installed without any issues.

**Comment by sindresorhus** [comment] 2017-09-22 09:18
Closing to clean up the issue tracker. If this is still an issue, open an issue on the relevant Imagemin plugin/binary repo instead.

**Closed by sindresorhus** 2017-09-22 09:18 UTC
