### ISSUE TITLE
Cannot build module

### ISSUE THREAD

**Issue by joeltello** [gruntjs/grunt-contrib-imagemin#324] opened 2015-10-17 00:37 UTC
I am getting this error when trying to install the module. 
node v4.2.1
grunt v4.5.0
grunt-cli v0.1.13

```
gifsicle@3.0.1 postinstall /Users/joel/Documents/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ⚠ Invalid non-string/buffer chunk
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/Users/joel/Documents/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/Users/joel/Documents/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/Users/joel/Documents/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/Users/joel/Documents/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:95:10)
    at DestroyableTransform.<anonymous> (/Users/joel/Documents/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:54:10)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/joel/Documents/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:460:10)
    at emitReadable (/Users/joel/Documents/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:454:7)
    at readableAddChunk (/Users/joel/Documents/workspace/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/decompress/node_modules/decompress-unzip/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:209:11)
```

**Comment by amunro** [comment] 2015-10-17 03:43
+1

**Comment by iq-dot** [comment] 2015-10-17 10:42
I have exactly the same

**Comment by shinnn** [comment] 2015-10-17 19:54
Duplicate of https://github.com/imagemin/imagemin/issues/127

**Closed** 2015-11-20 19:36 UTC
